# Site settings
title: 我的 AI 探索空間
SEOTitle: 我的 AI 探索空間 | AI Blog
header-img: https://images.unsplash.com/photo-1518770660439-4636190af475?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80 # 建議替換成您自己的 AI 主題圖片路徑，例如 img/ai-header-bg.jpg
email: leohu0710@gmail.com
description: "這裡是我的 AI 學習與分享園地"
keyword: "人工智慧, AI, 機器學習, 深度學習"
url: "https://LeoHu.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: LeoHu
zhihu_username: LeoHu
github_username: LeoHu # 請替換成您的 GitHub 用戶名
twitter_username: LeoHu
facebook_username: LeoHu
#linkedin_username:  LeoHu

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: Asia/Taipei

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: LeoHu

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-XXXXX-Y" # Please use your own track id
ga_domain: LeoHu.github.io # Please use your own domain, and update "url" above

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "對人工智慧充滿好奇的探索者 <br> 分享學習 AI 的筆記與心得"
sidebar-avatar: https://images.unsplash.com/photo-1527980965255-d3b416303d12?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=880&q=80 # 建議替換成您自己的頭像圖片路徑或 URL

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends: []
